# unset all of the values defined
# when including target_lib.cmake or target_exe.cmake
unset(ADDITIONAL_HEADERS)
unset(ADDITIONAL_SOURCES)
unset(AIO_SOURCE)
unset(AUTO_AIO)
unset(HEADERS)
unset(INSTALL_DESTINATION)
unset(LIB_TYPE)
unset(RUN_LIB_SUITE_TARGET)
unset(SOURCES)
unset(SOURCES_GLOB)
unset(TARGET)
unset(TEST_HEADERS)
unset(TEST_SOURCES)
