// bng_engine_cbindings.cpp v0.1.0 generated by gen_api_sources.py 2025-01-09 14:35:54.132514
#include "bng_engine_cbindings.h"
#include "bng_engine.h"
#if defined(__cplusplus)
extern "C" {
#endif // defined(__cplusplus)
#if defined(__cplusplus)
} // extern "C"
#endif // defined(__cplusplus)
